USE DATABASE AIRBNB;

USE SCHEMA STAGING;

CREATE OR REPLACE STAGE INT_SRC_FILES
 FILE_FORMAT = AIRBNB.STAGING.FF_CSV_FILES;

SHOW FILE FORMATS;

LIST @INT_SRC_FILES;

SELECT $1 FROM @INT_SRC_FILES/bookings.csv;
