USE DATABASE HMS;

USE SCHEMA BRONZE;

CREATE OR REPLACE STAGE EXT_HMS_FILES
 STORAGE_INTEGRATION = AWS_S3_INT
 URL = 's3://siva-snowflake/snowflake-dbt/Airbnb Data/'
 FILE_FORMAT = HMS.BRONZE.FF_CSV_FILES;

SHOW STORAGE INTEGRATIONS;

SHOW FILE FORMATS;

LIST @EXT_HMS_FILES;
